apiVersion: v1
kind: Service
metadata:
  name: reminders-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: reminders-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
